### ISSUE TITLE
Include working example

### ISSUE THREAD

**Issue by podlebar** [VPenkov/okayNav-vanillaJS#2]
Would it be possible to provide a working exampleand also include the needed CSS Files to make it work?

would be great..

**Comment by ACXgit** [comment]
Hello, it would be very useful, as it seems that the HTML markup is different from the one generated by the jQuery version, so the CSS used in that example on Codepen is not quickly reusable.

I'm also unable to get it working properly, as in my case it always displays the dropdown menu and not the default menu, no matter the viewport width. Without a live example to compare to it's hard to debug.

**Comment by atelierbram** [comment]
Even a [link to a demo on Codepen](https://codepen.io/jonneal/pen/wGwjZN) in the README would be helpful ...
